name: Extract ZIP

on:
  push:
    branches:
      - main
    paths:
      - "html.zip"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          unzip -o "html.zip" -d . || [ $? -eq 1 ]

      - name: Remove ZIP
        run: rm -f "html.zip"

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Extract ZIP"
          git push
